version: '3.1'

services:
  db:
    build: .
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB = postgres

  dbtest:
    build: .
    container_name: test-db
    restart: no
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
